### ISSUE TITLE
Evaluation output names for SipMask-VIS

### ISSUE THREAD

**Issue by gauravmunjal13** [JialeCao001/SipMask#11]
Hi Team,

I am reaching out regarding the output names during the evaluation of SipMask-VIS. The present code requires video ids to start from 1, however, it saves the output videos starting from 0, thereby mapping 1 to 0 and henceforth. 

Also, I am not sure if the above mismatch is the reason that the value of average precision is 0 at the end, while the model does a good job in detecting and tracking the objects in the output frames.

Second, in the saved path, the output misses some frames in the sequence. However, in the results.pkl.json file, the length of segmentations corresponding to a video is correct. From my analysis, it is skipping frames with None as the segmentation value. 

I really appreciate your thoughts if I am missing anything. 

Thanks!

**Comment by JialeCao001** [comment]
@gauravmunjal13 Hi. Thanks for your interest. (1) The video id for evaluation and  saved reasults can be different because the code saving results is written by me and the code for evaluation is provided by the official dataset. But I think it is not necessary to be same because we just need to visualize the results in order. For evaluation, you should follow official dataset. (2) With our provided model, we do not get the ap of 0. I am not sure about your reason. (3) It will skip frames with None. If you want to save results in each image, you can set a lower threshold in configs file.

**Comment by gauravmunjal13** [comment]
Thanks, @JialeCao001  for your response!

Could you please suggest where are you saving the frames/results?  I came across function _show_results()_ in _inference.py_ code under mmdet/apis. But it doesn't save the results. 

Meanwhile, I tried to write a code snippet to plot and save results using **results.pkl.json** output file so that I can filter results based on score. The output displayed by your code is correct, however, the one using my code snippet is drifted. Probably size or scale issue.

I am decoding the segmentations and applying on the image as:
```
mask = maskUtils.decode(segm)
im_pred = apply_mask(im_pred, mask, (0.0,1,0.0)).astype(np.uint8)
```

where, apply_mask() is:
```
def apply_mask(image, mask, color, alpha=0.5):
     for c in range(3):
        image[:, :, c] = np.where(mask == 1,image[:, :, c] *(1 - alpha) + alpha * color[c] * 255,image[:, :, c])
     return image
```

Last, it is suggested on Readme that there are two versions of SipMask as High-Accuracy and Real-Time Fast. How do I know which one I am using and how to switch to the other?

**Comment by JialeCao001** [comment]
@gauravmunjal13 Hi. I can get all the things that you say. Here, I try to ask your questions.
(1) I am not very sure that the mmdetection will filter out objects of small-scale objects. If I am free, I can check this problem.
(2) SipMask is more useful for large-scale objects from our experiments.
(3) In Readme, I introduce how to save the results of youtube-vis. Please use the the following command:
python tools/test_video.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] --eval segm --show --save_path= ${SAVE_PATH}
And the corresponding show_result function is in base.py as
https://github.com/JialeCao001/SipMask/blob/f7b035232ae3ff8d7171fd98b80efdbac926cbd6/SipMask-VIS/mmdet/models/detectors/base.py#L109
(4) Instance segmentation in images has two versions of SipMask. For video instance segmentation, we only provide SipMask-VIS.

**Comment by gauravmunjal13** [comment]
Hi @JialeCao001 

I may have figured out the reason why my code for plotting and saving the results is not working properly. 

The input to the model is images and segmentations corresponding to size (512,512). The model produces an output as results.pkl.json in which the **size** of segmentations is (512,512) and the mask obtained after decoding them is also (512,512). However, the issue was that these segmentations seems to be drifted towards the top left and smaller in size, but were correct in your saving results.

My analysis is that you are saving the images as of size (360,360) but the segmentations are of size (512,512). Does it mean there is a discrepancy in producing results or am I missing anything?

Thanks!

**Comment by JialeCao001** [comment]
@gauravmunjal13 Hi. If you save images with the following code, can you get the right results?
python tools/test_video.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] --eval segm --show --save_path= ${SAVE_PATH}

**Comment by gauravmunjal13** [comment]
> @gauravmunjal13 Hi. If you save images with the following code, can you get the right results?
> python tools/test_video.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] --eval segm --show --save_path= ${SAVE_PATH}

Yes! But the resulting images are resized to (360,360) while the input images were of size (512,512).

**Comment by JialeCao001** [comment]
@gauravmunjal13 okay. I know what you say. The saved images is the same to the rescaled input image for network, which may be different from original image.

**Comment by gauravmunjal13** [comment]
But it seems not. I used your code (show_result() method in base.py) as the reference to plot and save results from results.pkl.json. 
First, I resized the image from (512,512) to (360,360).
Second, the mask obtained is of size (512,512), but I slice it as `mask = mask[:h, :w]`, where h and w are 360. 

This shows the correct results. 

Thanks @JialeCao001 for your support!

**Comment by gauravmunjal13** [comment]
Hi @JialeCao001 ,

Let me know if I can provide more information or not clear in explaining.

Thanks!

**Comment by JialeCao001** [comment]
@gauravmunjal13 I am not sure about your problem. I donot get a mAP of 0 on youtube-vis test set.

**Comment by gauravmunjal13** [comment]
Hi @JialeCao001 ,
 I think we can close this issue. As discussed in the mails, that the following command produces the correct output (results.pkl.json):
`python tools/test_video.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] --eval segm`

But the following command doesn't results in the correct output file (results.pkl.json) in terms that the annotations aren't resized back to the orignal size:
`python tools/test_video.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] --eval segm --show --save_path= ${SAVE_PATH}`

Thanks!
