### ISSUE TITLE
fatal error: cpu/vision.h: No such file or directory  #include "cpu/vision.h"

### ISSUE THREAD

**Issue by NaeemKhan333** [JialeCao001/SipMask#16]
I have run the following command

python setup.py build develop --no-deps

I am facing following error 

fatal error: cpu/vision.h: No such file or directory
 #include "cpu/vision.h"

**Comment by JialeCao001** [comment]
@NaeemKhan333 Which code? In addtion, could you provide more details, such as the version of pytorch, cuda, and mmcv?

**Comment by NaeemKhan333** [comment]
I have
 cuda 10.2
torch (1.6.0)
torchvision (0.7.0)

**Comment by JialeCao001** [comment]
@NaeemKhan333 Maybe you can try use my settings: PyTorch1.1.0 and cuda9.0/10.0.

**Comment by NaeemKhan333** [comment]
@JialeCao001 
Traceback (most recent call last):
  File "tools/test_net.py", line 4, in <module>
    from fcos_core.utils.env import setup_environment  # noqa F401 isort:skip
ModuleNotFoundError: No module named 'fcos_core'

**Comment by NaeemKhan333** [comment]
It is due to pytorch and torch version issue

```
pip3 install torch==1.4 torchvision==0.5

```
Thanks for help
