### ISSUE TITLE
Inference Script for SipMask-benchmark (image instance segmentation) on input image

### ISSUE THREAD

**Issue by NaeemKhan333** [JialeCao001/SipMask#17]
@JialeCao001 Thanks for nice work . I have single image, how I can get inference result on that image and show it using open cv for SipMask-benchmark (image instance segmentation). Can you guide me about it Thanks

**Comment by JialeCao001** [comment]
@NaeemKhan333 Thanks for your interest. I take a look at the readme of original maskrcnn-benchmark and find that it provides the codes. https://github.com/facebookresearch/maskrcnn-benchmark#inference-in-a-few-lines
Maybe you can do it on my code, because my code is built on maskrcnn-benchmark.

**Comment by NaeemKhan333** [comment]
@JialeCao001 Ok Thanks

**Comment by aniketzz** [comment]
Hi @NaeemKhan333, I am also trying to display the result. If you have done it can u please share the script?
