### ISSUE TITLE
About the evaluation in the codalab

### ISSUE THREAD

**Issue by hero-y** [JialeCao001/SipMask#21]
Hi, when I try to upload the json file to the codalab for vis, the website gives a piece of error information "Invalid file type (application/json)." Is it normal?

**Comment by YYlvsy** [comment]
Hi,I also met this problem.Have you solved it?If so, please tell me how to evaluate the result.Thank you very much!!

**Comment by JialeCao001** [comment]
@YYlvsy Do you rename the file as results.json and convert it to zip format?
