### ISSUE TITLE
'SipMask is not in the detector registry'

### ISSUE THREAD

**Issue by amaanda** [JialeCao001/SipMask#22]
greetings, thanks for sharing your work!
i'm trying to run the demo on an ec2:

``python3 ./demo/sipmask_demo.py ./configs/sipmask/sipmask_r50_caffe_fpn_gn_1x.py ./sipmask_r50_caffe_1x.pth ./demo/demo.jpg --out ./demo/aa.jpg
``

 but i keep getting the following error:
 
``File "/home/ubuntu/.local/lib/python3.6/site-packages/mmcv/utils/registry.py", line 164, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'SipMask is not in the detector registry'``

i followed all the steps on the installation of mmcv and mmdetection, and then cloned the sipmask repo. do you know what might be causing this?
thanks in advance!

**Comment by amaanda** [comment]
python 3.6.9, cuda 10.0, pytorch 1.4.0, mmcv 1.1.5, mmdet 2.5.0

**Comment by JialeCao001** [comment]
@amaanda Thanks for interest. Maybe the enviroment doesnot match. Please refer to the Readme for the version about pytorch, mmcv. In addition, you donot need to install a new mmdetection because our project contains the mmdetection.

**Comment by amaanda** [comment]
Yep! My mistake was that I was trying to install mmdetection before even cloning into your repo. Thanks! :)
