### ISSUE TITLE
ModuleNotFoundError: No module named 'pycocotools.ytvos'

### ISSUE THREAD

**Issue by jinw960** [JialeCao001/SipMask#23]
Hi.

I followed the instruction to run the SipMask-VIS, following your readme (using docker build).

When I run test, "python tools/test_video.py configs/sipmask/sipmask_r50_caffe_fpn_gn_1x.py work_dir/sipmask_r50_caffe_1x.pth --out tmp.pkl --eval segm",

I got an error message
" 
 File "/workspace/sipmask/SipMask/SipMask-VIS/tools/../mmdet/core/evaluation/coco_utils.py", line 5, in <module>
    from pycocotools.ytvos import YTVOS
ModuleNotFoundError: No module named 'pycocotools.ytvos'
"

I tried to clone the repository https://github.com/youtubevos/cocoapi,
and install following the instruction of the youtubevos/cocoapi, but the problem have not been solved.

What should I do?

**Comment by jinw960** [comment]
I just solved the problem by adding ytvos.py and ytvoseval.py file into my package!

**Comment by Foggor** [comment]
Thank you very much
