### ISSUE TITLE
Results have no predicitons

### ISSUE THREAD

**Issue by jinw960** [JialeCao001/SipMask#24]
Hi!
I run the test code

tools/test_video.py configs/sipmask/sipmask_r50_caffe_fpn_gn_1x.py work_dir/sipmask_r50_caffe_1x.pth --out sipmask.pkl --eval segm

using the pth file downloaded from your readme.

However, when the test finished, the outputs of the model is empty. Where should I fix?

**Comment by JialeCao001** [comment]
@jinw960 Thanks for your interest. The generated json file is 0kb?

**Comment by jinw960** [comment]
Yes, and when I printed out the outputs in tools/test_video.py main(), it was also a empty list.

**Comment by JialeCao001** [comment]
@jinw960 When you run the code, does it have any warning about missing somethings like weights?

**Comment by jinw960** [comment]
unexpected key in source state_dict: bbox_head.cls_convs.2.conv.weight, bbox_head.cls_convs.2.gn.weight, bbox_head.cls_convs.2.gn.bias, bbox_head.reg_convs.3.conv.weight, bbox_head.reg_convs.3.gn.weight, bbox_head.reg_convs.3.gn.bias

missing keys in source state_dict: bbox_head.track_convs.0.conv.weight, bbox_head.track_convs.0.gn.weight, bbox_head.track_convs.0.gn.bias, bbox_head.track_convs.1.conv.weight, bbox_head.track_convs.1.gn.weight, bbox_head.track_convs.1.gn.bias, bbox_head.sipmask_track.weight, bbox_head.sipmask_track.bias

Here, and I checked the bbox_list = self.bbox_head.get_bboxes(*bbox_inputs) in mmdet/models/detectors/single_stage.py simple_test(). It the value is empty

**Comment by JialeCao001** [comment]
@jinw960 Please check your loaded model and configure file: https://drive.google.com/file/d/1HIQyzApw6b7CUdTxchZT_TIcGYcDodbn/view?usp=sharing
https://github.com/JialeCao001/SipMask/blob/master/SipMask-VIS/configs/sipmask/sipmask_r50_caffe_fpn_gn_1x.py

**Comment by jinw960** [comment]
It works, thanks! I think I used wrong pth..
