### ISSUE TITLE
Sipmask-VIS :output_size of sipmask_r50_caffe_1x.pth do not match 

### ISSUE THREAD

**Issue by YYlvsy** [JialeCao001/SipMask#31]
First thanks for providing the code of this wonderful work!
Here's the problem.
When loading from './../SipMask-mmdetection/work_dirs/sipmask_r50_caffe_1x.pth',
**the output size** of this pretrained model do not match it of the VIS model.Since the number of classes of the pretrained model is **80,**different from it (which is **40**) of the VIS model.
Please tell me how to deal with this problem. Thank you!!

**Comment by JialeCao001** [comment]
@YYIvsy Hi. Thanks for your interest. In fact, it is different. Does it report the error? or Just a warning? If it reports error, maybe you need to change the version of mmcv. Please use mmcv0.2.12.

**Comment by YYlvsy** [comment]
> @YYIvsy Hi. Thanks for your interest. In fact, it is different. Does it report the error? or Just a warning? If it reports error, maybe you need to change the version of mmcv. Please use mmcv0.2.12.

Thanks a lot! I checked the version of mmcv,it turned out that I was using mmcv 0.2.10.I've already changed the version .Hope it works.

**Comment by YYlvsy** [comment]
@JialeCao001
the match error became warning but new error as above occurred>_<.
 `2021-01-22 13:36:44,653 - INFO - workflow: [('train', 1)], max: 12 epochs
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of b
ounds"` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of b
ounds"` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of b
ounds"` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [99,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of b
ounds"` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [100,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of
bounds"` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [101,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of
bounds"` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/ATen/native/cuda/IndexKernel.cu:53: lambda [](int)->auto::opera
tor()(int)->auto: block: [20,0,0], thread: [102,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of
bounds"` failed.`
