### ISSUE TITLE
能否给一个生成VIS的预测结果的demo.py 的示例？

### ISSUE THREAD

**Issue by Xiaoqi-Zhao-DLUT** [JialeCao001/SipMask#4]

**Comment by JialeCao001** [comment]
Hi. I use the file of test_video.py to save the image results to ${SAVE_PATH} as follows.
```shell
python tools/test_video.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] --eval segm --show --save_path= ${SAVE_PATH}
```
Is it okay for you?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@JialeCao001 非常感谢你更新的vis code。很不错的工作！

**Comment by JialeCao001** [comment]
@Xiaoqi-Zhao-DLUT 谢谢。你们的工作也非常不错。

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@JialeCao001 你好，还想再问个问题。你是否用过除Youtube VIS这个数据集以外的，数据集进行训练过？ 我想自己训一下自己的数据集，但不是很清楚该如何生成与Youtube VIS一样格式的train.json。 我看官网也没有提供生成的code.

**Comment by JialeCao001** [comment]
@Xiaoqi-Zhao-DLUT 我没有跑过其他数据集，不过感觉转成youtube-vis的json格式问题不大。youtube-vis评价需要json格式的结果，用到了results2json_videoseg这个函数。基于这个函数和youtube-vis的cocoapi，我觉得应该可以实现你的需求。
https://github.com/JialeCao001/SipMask/blob/d1b68d545383114fe43fe247e65eddc60125cfb5/SipMask-VIS/mmdet/core/evaluation/coco_utils.py#L205
