### ISSUE TITLE
cannot import name 'YTVOS' from 'pycocotools.ytvos'

### ISSUE THREAD

**Issue by aniketzz** [JialeCao001/SipMask#42]
I got the error **cannot import the name 'YTVOS' from 'pycocotools.ytvos'** while executing train.py from SipMask_Vis. I have followed the **https://github.com/youtubevos/cocoapi** link to install pycocotools.

**Comment by JialeCao001** [comment]
@aniketzz You can try download it and install it on your project conda enviroment.

**Comment by aniketzz** [comment]
Thanks, I did a fresh installation in the project directory and it worked.
