### ISSUE TITLE
关于SipMask-VIS的预训练模型

### ISSUE THREAD

**Issue by zsy-hub** [JialeCao001/SipMask#48]
谢谢大佬分享工作。我下载了SipMask-mmdetection的训练模型当作VIS的预训练模型，但是加载模型时出现错误：
RuntimeError:While copying the parameter named bbox_head.fcos_cls.weight,whose dimension in the model are torch.size([40,256,3,3]) ang whose dimension in the checkpoint are torch.size([80,256,3,3]).

这个错误应该是由于coco和youtube-vis数据集类别不一致导致的，请问我是不是下载错了预训练模型。

**Comment by JialeCao001** [comment]
@zsy-hub 对，类别不一致导致的。没有下错，基于它训练就行。

**Comment by zsy-hub** [comment]
> @zsy-hub对,类别不一致导致的。没有下错,基于它训练就行。

谢谢回复。
但是训练会报错，我修改了代码，不加载bbox_head.fcos_cls.weight和bbox_head.fcos_cls.bias就可以运行，请问您也是这样操作的嘛

**Comment by JialeCao001** [comment]
@zsy-hub 我用的mmcv版本应该是会忽略这个不一致的（只是警告不一致，不会报错）。但是你这种做法也挺好的，只要保证其他部分用的是预训练模型的就行。

**Comment by zsy-hub** [comment]
> @zsy-hub 我用的mmcv版本应该是会忽略这个不一致的。但是你这种做法也挺好的，只要保证其他部分用的是预训练模型的就行。

好的好的 非常感谢！
