### ISSUE TITLE
SipMask-VIS tracking implementation

### ISSUE THREAD

**Issue by ollefager** [JialeCao001/SipMask#50]
Hi,

In your paper you say that you match instances across frames similar to MaskTrack R-CNN. Where in your code do you perform this matching? and where can I adjust the parameters such as how many frames in the past to consider (beta in the MOTS paper) and the distance threshold (delta in the MOTS paper)?

**Comment by JialeCao001** [comment]
@ollefager During Inference, we just compare the previous one frame with current frame. Please refer https://github.com/JialeCao001/SipMask/blob/bc63fa93f9291d7b664c065f41d937a65d3c72fd/SipMask-VIS/mmdet/models/anchor_heads/sipmask_head.py#L619

**Comment by ollefager** [comment]
Thank you! Hmm, maybe I'm misunderstanding you. Because from my results I see that a specific track_id can disappear for a couple of frames to then appear again. This seems to indicate that the tracks are being saved for a number of frames.

**Comment by JialeCao001** [comment]
@ollefager The code save the last features of each previous object in memory.

**Comment by ollefager** [comment]
yes, so in each frame you also compare to the features of the objects in memory? If you only compare to the objects in the previous frame how could an object that has appeared earlier but does not appear in the previous frame, appear in the current frame?

**Comment by JialeCao001** [comment]
Yes. You are right. We only save one feature for each existed object.

**Comment by ollefager** [comment]
Okay. So do you ever remove an object from memory? Like if it hasn't appeared for a number of frames?

**Comment by ollefager** [comment]
If you don't mind I have another question. When comparing feature vectors you seem to compute their dot product, this line https://github.com/JialeCao001/SipMask/blob/bc63fa93f9291d7b664c065f41d937a65d3c72fd/SipMask-VIS/mmdet/models/anchor_heads/sipmask_head.py#L630
I don't really see how this measures their similarity however, as a feature vector with large values would score higher than a more similar feature vector with lower values, could you maybe explain?

**Comment by JialeCao001** [comment]
The dot product is used to compute the feature similarity. L638-L643 select the best match.

**Comment by ollefager** [comment]
Okay, thank you very much for your time!
