### ISSUE TITLE
SipMask-VIS Build Issue

### ISSUE THREAD

**Issue by gauravmunjal13** [JialeCao001/SipMask#9]
Hi,

Many thanks for sharing your work on instance segmentation!

I am writing regarding the error during installation of SipMask-VIS code. On running setup.py file from the SipMask-VIS repo ( as python setup.py build_ext install), I am getting the following error:
"_distutils.errors.DistutilsSetupError: each element of 'ext_modules' option must be an Extension instance or 2-tuple_"

On debugging, the error is happening due to extension checking at function "def check_extensions_list(self, extensions)" in the file ".../lib/python3.7/distutils/command/build_ext.py".

This instance checking fails for mmcv extension: setuptools.extension.Extension('mmcv._flow_warp_ext'). It is strange though because the mmcv._flow_warp_ext is a correct extension instance. 

At first, logically, it should not fail while instance checking because the extension is of correct instance (setuptools.extension.Extension). Second, this is happening while installing mmcv 1.1.1 (as best match for mmcv>=0.2.10) as part of the setup.py code flow.

How shall I resolve this error? I even tried pre-installing mmcv-full both directly and compiled from source, both the same error happens. Shall I explicitly pre-install mmcv=0.2.1 as mentioned in your settings?

Let me know if I can provide further details. Looking forward to hearing from you!

Thanks!

**Comment by JialeCao001** [comment]
@gauravmunjal13 Could you try to install it using my settings: PyTorch1.1.0, cuda9.0/10.0, and mmcv0.2.1.

**Comment by gauravmunjal13** [comment]
Many thanks @JialeCao001 for your reply!

Yes, I did try with the same settings, with mmcv 0.2.1, it seems that the build is successful, with the last output log as:
`Finished processing dependencies for mmdet==1.0rc0+unknown`

However, while running training file dist_train.sh, it gives the following runtime error:
`ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/.../SipMask/SipMask-VIS/tools/../mmdet/ops/dcn/__init__.py)`

From the build logs, it does seem that it builds the extension "mmdet.ops.dcn.deform_conv_cuda". 

Also, I did follow the error on the issues in mmdetection repo but haven't figured out how to resolve it in my case. I have followed the instructions as stated to install the mmdetection.

Any suggestions?

**Comment by JialeCao001** [comment]
@gauravmunjal13 I feel that you still donot compile the project successfully.  Could you provide more details about the settings? Is it installed in conda? I suggest that you use my pytorch version.

**Comment by gauravmunjal13** [comment]
Thanks, @JialeCao001 for your message!

**Here are my settings:** 
PyTorch 1.1.0
Torchvision 0.3.0
CUDA version 10.0
Cudatoolkit 10.0
mmcv 0.2.10
pycocotools 2.0
mmdet 1.0rc0+unknown
GCC 6.5.0

**Here is the list of instructions I followed:**
1. conda create -n sip-mask python=3.7 -y
2. conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
3. pip install mmcv==0.2.10
4. pip install git+https://github.com/youtubevos/cocoapi.git#"egg=pycocotools&subdirectory=PythonAPI"
5. git clone https://github.com/open-mmlab/mmdetection.git
6. cd mmdetection
7. python setup.py develop
8. cd ..
9. git clone https://github.com/JialeCao001/SipMask.git
10. cd SipMask/SipMask-VIS
11. python setup.py build_ext install

On running the 11th step, there are no errors and seems that the build is successful. 

After that on running _./tools/dist_train.sh_ with the config file and GPU number, it gives the same error:
`ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/home/.../SipMask/SipMask-VIS/tools/../mmdet/ops/dcn/__init__.py)`

Possibly, I am missing something in the installation. Please let me know if I can provide further information.

Thanks!

**Comment by JialeCao001** [comment]
@gauravmunjal13 Hi. You do not need to download the newest mmdetection and compile it (steps6-8), become our sipmask contains mmdetection of an old version. Try the command "python setup.py develop" after step 11.

**Comment by gauravmunjal13** [comment]
@JialeCao001 
Great! This solves the issue. Many thanks for your help!
